=== sanjeev11235/FC/web/WEB-INF/conf/jchatbox.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- jChaBox DTD - JavaZOOM -->
<!ELEMENT jChatBox (LOGFOLDER?, BACKUPFILE?, SYSTEMLOGIN?, SYSTEMPASSWORD?, SYSTEMEMAIL?, TIMEOUT?, COOKIEID?, USERSESSIONID?, LICENSE?, FILTERS?, TRANSCRIPT?, LANGUAGES)>
<!--Folder containing log files-->
<!ELEMENT LOGFOLDER (#PCDATA)>
<!--Backup Filename-->
<!ELEMENT BACKUPFILE (#PCDATA)>
<!--System user login-->
<!ELEMENT SYSTEMLOGIN (#PCDATA)>
<!--System user password-->
<!ELEMENT SYSTEMPASSWORD (#PCDATA)>
<!--System user email-->
<!ELEMENT SYSTEMEMAIL (#PCDATA)>
<!--Session Timeout in ms-->
<!ELEMENT TIMEOUT (#PCDATA)>
<!--CookieID (deprecated since 2.2.1)-->
<!ELEMENT COOKIEID (#PCDATA)>
<!--USERSESSIONID (advanced)-->
<!ELEMENT USERSESSIONID (#PCDATA)>
<!--License file-->
<!ELEMENT LICENSE (#PCDATA)>
<!--List of filters-->
<!ELEMENT FILTERS (FILTER*)>
<!--Filter's class name - Full qualified-->
<!ELEMENT FILTER (#PCDATA)>
<!--Transcript implementation -  Full qualified class name-->
<!ELEMENT TRANSCRIPT (#PCDATA)>
<!--List of listeners-->
<!ELEMENT LISTENERS (LISTENER*)>
<!--Listener's class name - Full qualified-->
<!ELEMENT LISTENER (#PCDATA)>
<!--List of languages-->
<!ELEMENT LANGUAGES (LANGUAGE+)>
<!ATTLIST LANGUAGES
    DEFAULT CDATA #REQUIRED
>
<!--Language-->
<!ATTLIST LANGUAGE
    NAME CDATA #REQUIRED
    RESOURCE CDATA #REQUIRED
>
<!ELEMENT LANGUAGE EMPTY>

=== sanjeev11235/FC/web/WEB-INF/conf/jchatbox.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE jChatBox SYSTEM "jchatbox.dtd">
<!-- jChatBox XML Configuration - JavaZOOM -->
<jChatBox>
    <LOGFOLDER>AUTOCONF</LOGFOLDER>
    <BACKUPFILE>AUTOCONF</BACKUPFILE>
    <SYSTEMLOGIN>system</SYSTEMLOGIN>
    <SYSTEMPASSWORD>5f4dcc3b5aa765d61d8327deb882cf99</SYSTEMPASSWORD>
    <SYSTEMEMAIL>jchatbox@javazoom.net</SYSTEMEMAIL>
    <TIMEOUT>300</TIMEOUT>
    <COOKIEID>JSESSIONID</COOKIEID>
    <USERSESSIONID>user</USERSESSIONID>
    <LICENSE>free-for-non-commercial.oxw</LICENSE>
    <FILTERS>
        <FILTER>jChatBox.Chat.Filter.HTMLFilter</FILTER>
        <FILTER>jChatBox.Chat.Filter.URLFilter</FILTER>
    </FILTERS>
    <TRANSCRIPT>jChatBox.Chat.Transcript.TextDump</TRANSCRIPT>
    <LISTENERS>
    </LISTENERS> 
    <LANGUAGES DEFAULT="english">
        <LANGUAGE NAME="english" RESOURCE="resources_en.xml"/>
        <LANGUAGE NAME="spanish" RESOURCE="resources_es.xml"/>
        <LANGUAGE NAME="portuguese" RESOURCE="resources_pt.xml"/>
        <LANGUAGE NAME="danish" RESOURCE="resources_da.xml"/>
        <LANGUAGE NAME="french" RESOURCE="resources_fr.xml"/>
        <LANGUAGE NAME="german" RESOURCE="resources_de.xml"/>
        <LANGUAGE NAME="dutch" RESOURCE="resources_nl.xml"/>
        <LANGUAGE NAME="swedish" RESOURCE="resources_sv.xml"/>
    </LANGUAGES>
</jChatBox>
